// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcodqs8yDpuhZj3-EPGCgTCwA1_DRRrsY',
    appId: '1:948920929657:web:63e12e65f790f05d3973a8',
    messagingSenderId: '948920929657',
    projectId: 'omega-f7d7d',
    authDomain: 'omega-f7d7d.firebaseapp.com',
    storageBucket: 'omega-f7d7d.appspot.com',
    measurementId: 'G-FFMRJ34TPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9CZNm2u9m1PWUXtS77ZOWk_uT_pgQZ28',
    appId: '1:948920929657:android:749e276ed4371f5c3973a8',
    messagingSenderId: '948920929657',
    projectId: 'omega-f7d7d',
    storageBucket: 'omega-f7d7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vowRwczo6l1edROhftgIHushdZIOrgo',
    appId: '1:948920929657:ios:384ea035040222253973a8',
    messagingSenderId: '948920929657',
    projectId: 'omega-f7d7d',
    storageBucket: 'omega-f7d7d.appspot.com',
    iosClientId: '948920929657-v9rjni6nbti4l6god7o662i9epbi6ut2.apps.googleusercontent.com',
    iosBundleId: 'com.example.omegaPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7vowRwczo6l1edROhftgIHushdZIOrgo',
    appId: '1:948920929657:ios:69ef3449698e2bb43973a8',
    messagingSenderId: '948920929657',
    projectId: 'omega-f7d7d',
    storageBucket: 'omega-f7d7d.appspot.com',
    iosClientId: '948920929657-p1ah4c37hji626of2nj24vui5vmb7vtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.omegaPractice.RunnerTests',
  );
}
